// src/lib/components/ThemeSwitch.svelte
<script>
    import { onMount } from "svelte";

    $: isDark = true
    onMount(() => {
        if(window.matchMedia && window.matchMedia('(prefers-color-scheme: light)').matches) isDark = false
    })
</script>

<svelte:head>
    <link rel="stylesheet" href={isDark ? "/themes/vardark.css" : "/themes/varlight.css"}>
    <link rel="stylesheet" href="/themes/var.css">
</svelte:head>
<div class="switch" on:click={() => isDark = !isDark}>
    <i class={"fas " + (isDark ? "fa-moon" : "fa-sun")}></i>
</div>

<style>
    .switch {
        border: 2px solid var(--text-color);
        padding: 5px;
        border-radius: 9999px;
        margin: 0px;
    }
    i {
        margin: 0px;
        padding: 0px;
        display: grid;
        place-items: center;
        color: var(--text-color);
    }
</style>

// src/components/ThemeSwitch.jsx
import React, { useState } from "react"
import { Helmet } from "react-helmet"
import * as styles from "../styles/ThemeSwitch.module.scss"

export default function ThemeSwitch() {
    const [isDark, setIsDark] = useState(getDefaultTheme())
    return (
        <div className={styles.themeswitch} onClick={() => setTheme(!isDark)}>
            <Helmet>
                <link
                    rel="stylesheet"
                    href={
                        isDark ? "/themes/vardark.css" : "/themes/varlight.css"
                    }
                />
                <link rel="stylesheet" href="/themes/var.css" />
            </Helmet>
            <i
                className={
                    "fas " + (isDark ? "fa-moon" : "fa-sun") + " " + styles.i
                }
            ></i>
        </div>
    )

    function getDefaultTheme() {
        const theme = window.localStorage.getItem("theme")
        if (theme === 'true') return true
        else if (theme === 'false') return false
        else if (typeof window !== "undefined") {
            if (
                window.matchMedia &&
                window.matchMedia("(prefers-color-scheme: dark)").matches
            )
                return true
        } else return false
    }
    function setTheme(isDark) {
        setIsDark(isDark)
        localStorage.setItem("theme", isDark)
    }
}
